# Generated by Django 3.1.4 on 2020-12-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
