# Generated by Django 3.1.4 on 2020-12-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones', '0002_smartphone_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='brand',
            field=models.CharField(default=' ', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='storage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='title',
            field=models.CharField(default=' ', max_length=80),
            preserve_default=False,
        ),
    ]
