# Generated by Django 3.1.4 on 2020-12-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones', '0005_auto_20201202_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='img',
            field=models.ImageField(null=True, upload_to='dashboards/smartphones/uploads/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smartphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphones.smartphone')),
            ],
        ),
    ]
