# Generated by Django 3.1.4 on 2020-12-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones', '0006_auto_20201202_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
