# Generated by Django 3.1.4 on 2020-12-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones', '0007_auto_20201202_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
